# The "params" section includes the configuration of a single Git repository that needs to be scanned.
# For Azure Repos, Bitbucket Server and GitHub with JFrog Pipelines or Jenkins, you can define multiple "params" sections one after the other, for scanning multiple
# Git repositories in the same organization.
- params:
    # Git parameters
    git:
      # [Mandatory]
      # Name of the git repository to scan
      repoName: frogbot-example

      # [Mandatory]
      # List of branches to scan
      branches:
        - main
    scan:
      includeAllVulnerabilities: true
      failOnSecurityIssues: true
